Added Trimming
RoboticsTeam4904/2017-Code pull request #13
Opened 2017-01-27 06:57 UTC by HowardStark

Added trimmable implementations of the PID Motion Controller as well as the PID Sensor, switched GearAlign to support trimming.

2017-01-27 07:00 UTC, HowardStark commented
For now, this fits in 2017 Code. However, this was designed with extensibility and code quality in mind so that the inclusion of the trimming system into standard will be seamless.

2017-01-27 07:08 UTC, leijurv approved these changes

2017-01-27 07:08 UTC, leijurv commented
Looks good to me. Good class hierarchy

2017-01-28 15:23 UTC, carturn commented on src/org/usfirst/frc4904/sovereignty/TrimmablePIDSensor.java
> +		return sensor.pidGet() + trimValue;
There may be issues with switching between kDisplacement and kRate with the same trim value.

2017-01-30 21:01 UTC, c0d3rman requested changes

2017-01-30 21:01 UTC, c0d3rman commented on src/org/usfirst/frc4904/sovereignty/TrimCommand.java
> +		UP(true), DOWN(false), LEFT(true), RIGHT(true);
One of LEFT/RIGHT should be false

2017-01-30 21:01 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +	private final GearAlign gearAlign = new GearAlign(new AligningCameraGRIP());
Probably should be protected in case other drivers extend it

2017-01-30 21:01 UTC, c0d3rman commented on src/org/usfirst/frc4904/sovereignty/TrimCommand.java
> +		return false;
This should finish immediately, no?

2017-02-02 01:02 UTC, HowardStark commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +	private final GearAlign gearAlign = new GearAlign(new AligningCameraGRIP());
This is no different from just instantiating the object within the bindCommands method in terms of subclass accessibility.

2017-02-02 06:28 UTC, c0d3rman requested changes
I like the core architecture very much. Some nitpicky changes requested.

2017-02-02 06:28 UTC, c0d3rman commented on .classpath
> +	<classpathentry kind="var" path="opencv" sourcepath="opencv.sources"/>
Please revert these changes, they are unnecessary

2017-02-02 06:28 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/Robot.java
> +	public void autonomousExecute() {
All Robot.Java changes seem to be unnecessary, please revert

2017-02-02 06:28 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/HumanInterfaceConfig.java
> +
Please remove this blank line, it's against convention but the formatter can't remove it

2017-02-02 06:28 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/HumanInterfaceConfig.java
> +	private HumanInterfaceConfig() {
Why does this class have a private constructor?

2017-02-02 06:28 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +	// TODO: Look at alternate pattern for storage of this object
I think this comment is no longer relevant?

2017-02-02 06:28 UTC, c0d3rman commented on src/org/usfirst/frc4904/sovereignty/TrimmablePIDSensorWrapper.java
> +
Same with this blank line

2017-02-02 06:28 UTC, c0d3rman commented on src/org/usfirst/frc4904/sovereignty/TrimmablePIDController.java
> +
Same with this blank line

2017-02-02 06:28 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/HumanInterfaceConfig.java
> +public class HumanInterfaceConfig {
Not sure about the name (not really a "Config" but can't come up with a better one - guess it's fine since it's yearly code

2017-02-02 06:30 UTC, HowardStark commented on src/org/usfirst/frc4904/robot/humaninterface/HumanInterfaceConfig.java
> +	private HumanInterfaceConfig() {
It should never be instantiated and that is the convention to ensure that.

2017-02-02 06:59 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/HumanInterfaceConfig.java
> +	private HumanInterfaceConfig() {
A bit spoopy but sure (we don't have it anywhere else).

2017-02-02 18:13 UTC, c0d3rman requested changes

2017-02-02 18:13 UTC, c0d3rman commented on src/org/usfirst/frc4904/sovereignty/TrimmablePIDSensorWrapper.java
> +
Please remove

2017-02-02 18:13 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/HumanInterfaceConfig.java
> +	private HumanInterfaceConfig() {
Can you put this on one line

2017-02-02 18:13 UTC, c0d3rman commented on .classpath
> +	<classpathentry kind="var" path="cscore" sourcepath="cscore.sources"/>
Can you remove this as well

2017-02-02 18:13 UTC, c0d3rman commented on .classpath
> +	<classpathentry kind="var" path="USERLIBS_DIR/navx_frc-sources.jar"/>
And this

2017-02-02 18:19 UTC, c0d3rman approved these changes

2017-02-02 18:20 UTC, merged