Lidar turn pid
RoboticsTeam4904/2017-Code pull request #19
Opened 2017-02-03 02:27 UTC by NikhilSuresh24

lidar pid makes lidar turn at about 240k mRPM +- 5k .

2017-02-03 06:28 UTC, c0d3rman commented
Please update this PR's labels if it is tested @NikhilSuresh24 @carturn

2017-02-03 06:35 UTC, carturn commented
Note that this has dependencies on [standard pull request #151](https://github.com/RoboticsTeam4904/standard/pull/151).

2017-02-09 01:53 UTC, carturn commented on src/org/usfirst/frc4904/robot/Robot.java
> +		RobotMap.Component.lidarMC.setPID(Lidar.LIDAR_TURN_P, Lidar.LIDAR_TURN_I, Lidar.LIDAR_TURN_D);
In my opinion, we should remove the SmartDashboard code now that testing has finished.

2017-02-11 21:30 UTC, leijurv commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		public static int lidarTurnP = 0;// put these in the constants section of RobotMap
this comment...

2017-02-18 00:00 UTC, ajnadel reviewed
Dependencies resolved.

2017-02-18 00:00 UTC, ajnadel commented on .classpath
> +	<classpathentry kind="var" path="cscore" sourcepath="cscore.sources"/>
@c0d3rman what should we do about this? If Eclipse adds these every time, let's just let it get merged in.

2017-02-18 00:00 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/Robot.java
> +	Command LidarCommand;
Fields should be camel case, but the leading letter should be lower case.

2017-02-18 00:00 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/Robot.java
> +		SmartDashboard.putNumber("LIDAR_P", Lidar.LIDAR_TURN_P);
Check out `SmartDashboardKey` for the first argument.

2017-02-18 00:03 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/commands/LidarTurner.java
> +			LogKitten.e("LIDAR error!");
.

2017-02-18 00:03 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/commands/LidarTurner.java
> +		RobotMap.Component.lidar.set(240000);
.

2017-02-18 00:03 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/subsystems/CANLidar.java
> +	public int[] readlidar() throws InvalidSensorException {
.

2017-02-18 00:03 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/subsystems/CANLidar.java
> +		write(new byte[] {0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01}); // Write to trigger read
.

2017-02-18 00:03 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/subsystems/LidarTurnPID.java
> +package org.usfirst.frc4904.robot.subsystems;
?

2017-02-18 00:23 UTC, c0d3rman approved these changes

2017-02-18 00:24 UTC, c0d3rman requested changes
Whoops, wrong PR.

2017-02-18 01:15 UTC, NikhilSuresh24 commented
Testerino'ed again.

2017-02-18 01:51 UTC, c0d3rman approved these changes

2017-02-18 01:52 UTC, ajnadel commented
Service was good, "food tasted like bed bugs" but would probably return on a rainy Sunday night.

2017-02-18 01:54 UTC, ajnadel approved these changes
Service was good, "food tasted like bed bugs" but would probably return on a rainy Sunday night.

2017-02-18 02:30 UTC, merged