Disable assistive align
RoboticsTeam4904/2017-Code pull request #32
Opened 2017-02-12 18:27 UTC by NikhilSuresh24

kills assistive align when button 6 is pressed, and reruns it when button 6 is released.

2017-02-21 02:15 UTC, ajnadel requested changes

2017-02-21 02:15 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		new Climb(() -> Math.max(0, -RobotMap.Component.driverXbox.rightStick.getY())).start();
This duplicated line 74.

2017-02-21 02:15 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(5).whenPressed(new Kill(alignAssist));
This should be `new Cancel()` instead of Kill.

2017-02-21 02:15 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(5).whenPressed(new Kill(alignAssist));
Actually, isn't there an while not pressed or something?

2017-02-21 02:16 UTC, ajnadel commented
Also, you have merge conflicts :/

2017-02-21 17:13 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(5).whenPressed(new Kill(alignAssist));
it's going to be a switch though, right? So it shouldn't matter???

2017-03-12 17:55 UTC, c0d3rman commented
Made obsolete by #69

2017-03-12 17:55 UTC, closed without merging