Merge Gear Align
RoboticsTeam4904/2017-Code pull request #4
Opened 2017-01-14 20:24 UTC by HowardStark

Added new gear aligning for 2017.
Reworked RobotMap to make more sense for autonomous.
Added vision system to support gear align.

- Minor text fixes.
- Raichu now has santa hat.

2017-01-14 20:48 UTC, carturn requested changes
Please remove .DS_Store
Also, replacing NathanGain with DefaultDriver is probably not good, especially as DefaultDriver is empty.

2017-01-14 21:00 UTC, carturn approved these changes

2017-01-14 21:02 UTC, carturn commented
Please make more relevant commit messages though.

2017-01-14 22:42 UTC, c0d3rman requested changes
DefaultDriver being empty is meh but we'll take care of it in a later PR. Please make the changes I've requested.

2017-01-14 22:42 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +
Please remove.

2017-01-14 22:42 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		Component.mainSubsystems = new Subsystem[] {};
I think I messed up this merge, we define mainSubsystems twice.

2017-01-14 22:42 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/DefaultDriver.java
> +
Please remove this blank line.

2017-01-14 22:42 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/operators/DefaultOperator.java
> +
Please remove this blank line.

2017-01-14 22:42 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/vision/AligningCamera.java
> +
Please remove this blank line.

2017-01-14 22:42 UTC, c0d3rman commented on src/org/usfirst/frc4904/sovereignty/strategies/GearAlign.java
> +	//
Please remove.

2017-01-15 04:08 UTC, c0d3rman requested changes
Can we please merge frame dropping separately? It's untested and I would like to merge basic gear align ASAP. Move it to a new branch please.

2017-01-16 05:02 UTC, c0d3rman approved these changes

2017-01-18 02:47 UTC, carturn commented on .classpath
> +	<classpathentry kind="lib" path="/Users/yonlern/wpilib/user/java/lib/CTRLib.jar"/>
This should be <classpathentry kind="lib" path="USERLIBS_DIR/CTRLib.jar"/>

2017-01-18 03:23 UTC, merged