made a switch that enables and disables automatic hopper movement and…
RoboticsTeam4904/2017-Code pull request #44
Opened 2017-02-18 19:15 UTC by NikhilSuresh24

… two buttons that when pressed change the hopper's position. made a switch that enables and disables automatic hopper movement

2017-02-20 21:50 UTC, c0d3rman requested changes
We need to think about how to do this better. We may need to do something similar to what we did with autoshifting.

2017-02-20 21:50 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(6).whenPressed(new SetOverride(true, new BallioOuttake()));
Move these down to where the normalDrive button is bound

2017-02-20 21:50 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(6).whenReleased(new SetOverride(false, new BallioOuttake()));
What about all the other places the hopper is shifted / will be shifted? Like the shooter? How do we deal with those?

2017-02-20 21:50 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/commands/BallioOuttake.java
> +		BallioOuttake.ballioCycleOverride = setValue;
Why is this static?

2017-02-20 21:50 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/commands/BallioOuttake.java
> +		BallioOuttake.ballioCycleOverride = setValue;
Also same thing about `setValue` -> `ballioCycleOverride`

2017-02-20 21:50 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(6).whenReleased(new SetOverride(false, new BallioOuttake()));
Or BallioCycle

2017-02-20 22:57 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(6).whenReleased(new SetOverride(false, new BallioOuttake()));
made all the commands with hopper shifts into runIfs that only run when override is false

2017-02-21 22:55 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(6).whenReleased(new SetOverride(false, new BallioOuttake()));
every place that set the hopper(Ballio) now is a runif that only runs when the override is off. There is another branch(the last one I made), which has accounts for all places the hopper is set, shooter included

2017-03-12 23:24 UTC, c0d3rman approved these changes
Still good by me.

2017-03-12 23:35 UTC, merged