when button10 pressed, hopper agitate
RoboticsTeam4904/2017-Code pull request #45
Opened 2017-02-18 19:16 UTC by NikhilSuresh24

hopper agitates when button 10 pressed

2017-02-19 00:35 UTC, billwpierce commented
Please test.

2017-02-19 21:58 UTC, billwpierce commented
@NikhilSuresh24 please test.

2017-02-20 21:42 UTC, c0d3rman requested changes

2017-02-20 21:42 UTC, c0d3rman commented on .classpath
> +	<classpathentry kind="var" path="USERLIBS_DIR/CTRLib-javadoc.jar"/>
Revert classpath changes

2017-02-20 21:42 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(9).whenPressed(new HopperAgitate());
List in numerical order

2017-02-21 02:06 UTC, ajnadel commented on .classpath
> +	<classpathentry kind="var" path="USERLIBS_DIR/navx_frc-sources.jar"/>
Dirty change stinky change take it away

2017-02-21 02:06 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		Component.teensyStick = new TeensyController(Port.HumanInput.teensyStick, 30);
Move magic number to constant in human interface config..?

2017-02-21 02:06 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		Component.teensyStick = new TeensyController(Port.HumanInput.teensyStick, 30);
Also will there really be 30 buttons?

2017-02-21 02:06 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/humaninterface/operators/DefaultOperator.java
> +		RobotMap.Component.teensyStick.getButton(9).whenPressed(new HopperAgitate());
I think you mean `onlyWhileHeld`, right?

2017-02-21 03:15 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		Component.teensyStick = new TeensyController(Port.HumanInput.teensyStick, 30);
just a placeholder

2017-02-21 05:24 UTC, ajnadel approved these changes

2017-02-21 05:26 UTC, c0d3rman approved these changes

2017-03-13 01:07 UTC, c0d3rman approved these changes

2017-03-13 01:12 UTC, c0d3rman approved these changes

2017-03-13 01:16 UTC, merged