Gear intake outtake
RoboticsTeam4904/2017-Code pull request #5
Opened 2017-01-16 19:39 UTC by NikhilSuresh24

Made gearIO subsystem and commands to intake and outtake gears

2017-01-16 20:22 UTC, ajnadel requested changes
Great job so far -- once you make these few small changes and @billwpierce finishes, this will come together perfectly.

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +			public static int gearSolenoidDown = 1;
Make sure all of these ports are correct ones (or heavily annotated to say they are WIP) before merging.

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +			public static final double WIDTH = 0;// all in inches
Helpful comment. :D

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		Component.navX = new NavX(SerialPort.Port.kOnboard);// TODO add encoders
NIT: Comment?

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/autonomous/AutonVomit.java
> +		requires(RobotMap.Component.chassis);
I don't think you have to require these as the command in the group will do that independently.

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/autonomous/AutonVomit.java
> +		addParallel(new ChassisMoveDistance(RobotMap.Component.chassis, AutonVomit.distance1, null, new Kill(this), RobotMap.Component.leftWheelEncoder));// in inches
Can you add a CustomPIDController or other MotionController?

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/autonomous/AutonVomit.java
> +		addSequential(new ChassisTurn(RobotMap.Component.chassis, 135, RobotMap.Component.navX, new Kill(this), null));// in degrees
Can you move 135 to a constant value so that it isn't a "magic number?"

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/autonomous/AutonVomit.java
> +	protected void execute() {}
NIT: You can delete initialize and execute for concision (if you want).

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/autonomous/AutonVomit.java
> +	protected void end() {}
NIT: Same with `end` and `interrupted`.

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/commands/GearIntake.java
> + *
NIT: Comment?

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/commands/GearIntake.java
> +	protected void execute() {}
NIT: See prev. comment about deleting unused methods.

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/commands/GearOuttake.java
> +public class GearOuttake extends Command {
High level feedback about this method and GearIntake: check out RockNRoller in 2016-Code.

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +	public void IntakeGear() {
Try `intakeGear` instead for capitalization.

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +		// Set the default command for a subsystem here.
Add `setDefaultCommand(new Idle());` here. This means that when any running command on the subsystem is cancelled, the Idle command runs instead. Idle literally does nothing: if a motor is running, it won't change it.

2017-01-16 20:22 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/commands/GearIntake.java
> + *
and all the other empty ones

2017-01-16 22:12 UTC, ajnadel requested changes
I promise I'll approve this, but first can you remove all the unused methods?

2017-01-16 22:12 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +			public static int gearSolenoidUp = 0;// ports are WIP
Noice.

2017-01-16 22:12 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		Component.navX = new NavX(SerialPort.Port.kOnboard);
Noice.

2017-01-16 22:12 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/autonomous/AutonVomit.java
> -package org.usfirst.frc4904.robot.autonomous;
Coolio.club
Having these as separate branches/PR's will make merging easier.

2017-01-16 22:12 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/commands/GearIntake.java
> +		super(GearState.INTAKE);
Noice.

2017-01-16 22:12 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/commands/GearSet.java
> +	// Called just before this Command runs the first time
Can you remove the unused methods like `initialize` and `end` and `interrupted` ?

2017-01-16 22:12 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +		setDefaultCommand(new Idle(this));
Noice.

2017-01-16 22:12 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +	public void setGear(GearState state) {
Noice

2017-01-16 22:51 UTC, ajnadel approved these changes
Neato LIDAR, dude.

2017-02-02 05:59 UTC, oldgalileo requested changes

2017-02-02 05:59 UTC, oldgalileo commented on build.properties
> -userLibs=lib/navXLibrary/navx_frc.jar
Changes to build.properties probably shouldn't be handled in this PR and rather a different branch.

2017-02-02 05:59 UTC, oldgalileo commented on src/org/usfirst/frc4904/robot/RobotMap.java
>  		public static class PWM {
This isn't the designated use for RobotMap. Move your constants into the classes they are used in. Use common sense for their placement. It's not easy but it will make it less messy.

2017-02-02 05:59 UTC, oldgalileo commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +			public static final double WIDTH = 0;// all in inches
This should be a JavaDoc on RobotMap or something else. This shouldn't be in an offhanded comment as that's a big note that should be referenced in a core place. Consider moving it to the [readme](README.md).

2017-02-02 05:59 UTC, oldgalileo commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +			public static final double WAIT_TIME = 0;
See comments on RobotMap.

2017-02-02 05:59 UTC, oldgalileo commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		public static GearIO gearIntakeOuttake;
This is a good use of RobotMap. Ideally, RobotMap should be a literal map of the robot, with subsystems and _maybe_ ports. That should be it.

2017-02-02 05:59 UTC, oldgalileo commented on src/org/usfirst/frc4904/robot/RobotMap.java
> -		Component.mainSubsystems = new Subsystem[] {Component.ballIntake, Component.ballDumper, Component.flywheel};
mainSubsystems shouldn't be removed.

2017-02-02 05:59 UTC, oldgalileo commented on src/org/usfirst/frc4904/robot/commands/GearIntake.java
> + *
Empty javadoc?

2017-02-02 05:59 UTC, oldgalileo commented on src/org/usfirst/frc4904/robot/commands/GearSet.java
> +	// Called repeatedly when this Command is scheduled to run
Comments on methods should be in the javadoc style.

2017-02-02 05:59 UTC, oldgalileo commented on src/org/usfirst/frc4904/robot/commands/GearSet.java
> +public class GearSet extends Command {
Add some basic implementation for this. It should be doable without having physical access to the robot.

2017-02-02 06:57 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/RobotMap.java
>  		public static class PWM {
I thought we said ports would stay in RobotMap since it's a map of the robot? These are PWM ports.

2017-02-02 06:57 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +			public static final double WAIT_TIME = 0;
Agreed here.

2017-02-16 02:07 UTC, billwpierce commented
@HowardStark not to be rude, but what's stopping you from accepting the review?

2017-02-16 02:51 UTC, leijurv commented
please resolve git merge conflicts in robotmap

2017-02-18 05:29 UTC, c0d3rman approved these changes

2017-02-18 15:38 UTC, carturn commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +	public static enum GearState {
Why not add the ramp state to this?

2017-02-18 15:38 UTC, carturn commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +	public void setRampState(DoubleSolenoid.Value value) {
This should take in an enum (or be merged with setState).

2017-02-18 15:39 UTC, carturn commented on src/org/usfirst/frc4904/robot/commands/GearioSet.java
> +		RobotMap.Component.gearIO.setState(GearIO.GearState.TRANSPORT);
I am a bit concerned about what this might do if a gear is stuck in the mechanism somewhere.

2017-02-18 15:40 UTC, carturn requested changes
Add some form of enum system for the ramp state.

2017-02-18 16:58 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +	public static enum GearState {
That was my issue - the ramp needs to be controlled independently from it. We put it out once at the beginning of the match, and only retract it for climbing.

2017-02-18 16:58 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +	public void setRampState(DoubleSolenoid.Value value) {
Agreed.

2017-02-18 16:59 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/commands/GearioSet.java
> +		RobotMap.Component.gearIO.setState(GearIO.GearState.TRANSPORT);
The reason for this was that the gull wings need to close, but I don't want to wait till we start intaking to close them.

2017-02-18 19:20 UTC, carturn approved these changes

2017-02-18 19:27 UTC, oldgalileo approved these changes

2017-02-18 19:27 UTC, HowardStark commented on src/org/usfirst/frc4904/robot/RobotMap.java
>  		public static class PWM {
Sure.

2017-02-18 19:32 UTC, merged