when button15 pressed disables all acceleration caps, when released, …
RoboticsTeam4904/2017-Code pull request #52
Opened 2017-02-19 23:00 UTC by NikhilSuresh24

switch that enables or disables all acceleration caps

2017-02-20 21:39 UTC, c0d3rman requested changes

2017-02-20 21:39 UTC, c0d3rman commented on .classpath
> +	<classpathentry kind="var" path="USERLIBS_DIR/CTRLib-javadoc.jar"/>
No please
Please cd to the root of your repo and run
```
git checkout master -- .classpath
git add .classpath
git commit
git push
```
The first command gets the version of .classpath master has

2017-02-21 02:03 UTC, ajnadel approved these changes

2017-02-21 02:03 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		public static EnableableModifier rightWheelAccelerationCap;
I don't love having non-material things here, but I can't think of a better place to keep these.

2017-02-21 02:03 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		Component.teensyStick = new TeensyController(Port.HumanInput.teensyStick, 30);
Are there actually 30 buttons? Also, can you move the number to a constant, maybe HumanInterfaceConfig.

2017-02-21 03:14 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/RobotMap.java
> +		public static EnableableModifier rightWheelAccelerationCap;
cool

2017-02-21 05:04 UTC, ajnadel approved these changes

2017-02-21 05:55 UTC, c0d3rman approved these changes

2017-02-22 20:54 UTC, widdakay commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(0).whenPressed(normalDrive);
Same as what aj said for this, and the rest of the constants for what the teensy uses

2017-03-13 00:59 UTC, merged