Manual ramp shift
RoboticsTeam4904/2017-Code pull request #53
Opened 2017-02-19 23:02 UTC by NikhilSuresh24

switch that turns off all automatic ramp shifting(including during climb) and 2 buttons that when pressed, shift ramp

2017-02-20 20:02 UTC, c0d3rman requested changes

2017-02-20 20:02 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/commands/Climb.java
> -	protected static final double MINIMUM_AXIS_VALUE_TO_FLIP_GEARIO_RAMP = 0.25;
Readd this

2017-02-20 20:02 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/commands/Climb.java
> +		if (RobotMap.Component.gearIO.isNotOverridden()) {
Move this back to execute

2017-02-20 20:02 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/commands/GearioIntake.java
> +		if (GearIO.rampOverride == false) {
No need to check `a == false`, you can use `!a`

2017-02-20 20:02 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/commands/SetRampState.java
> +		// TODO Auto-generated method stub
Remove this comment

2017-02-20 20:02 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/commands/SetRampState.java
> +		return false;
Why does this never end?

2017-02-20 20:02 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/commands/SetRampState.java
> +		RobotMap.Component.gearIO.setRampState(state);
This will change the ramp state when you _construct_ the command, not _start_ it.

2017-02-20 20:02 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +	public static boolean rampOverride;
Why is this static?

2017-02-20 20:02 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +		if (GearIO.rampOverride == false) {
Same as above (don't use `== false`)

2017-02-20 20:02 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +	public void setOverride(boolean setValue) {
With setters, just like constructors, the method argument should be the same name as the property - eg. `this.rampOverride = rampOverride`

2017-02-20 20:13 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +	public static boolean rampOverride;
the override should apply to all gearios, not just one instance

2017-02-20 20:13 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +	public void setOverride(boolean setValue) {
its from an interface. It wouldn't be an @override then

2017-02-20 20:20 UTC, kirbyblox commented
Hi

2017-02-20 21:37 UTC, c0d3rman requested changes

2017-02-20 21:37 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/commands/SetRampState.java
> +	protected RampState state;
make final

2017-02-20 21:37 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/subsystems/GearIO.java
> +		if (RobotMap.Component.gearIO.isNotOverridden()) {
This is within geario... why access the one in RobotMap?
Also we're never overriden when we construct

2017-02-20 21:44 UTC, c0d3rman approved these changes

2017-02-20 23:31 UTC, c0d3rman commented on src/org/usfirst/frc4904/robot/humaninterface/drivers/NathanGain.java
> +		RobotMap.Component.teensyStick.getButton(0).whenPressed(normalDrive);
Move these to the operator

2017-02-21 01:05 UTC, c0d3rman approved these changes

2017-02-21 01:10 UTC, merged