Camera calibration
RoboticsTeam4904/2017-Code pull request #57
Opened 2017-02-21 23:48 UTC by CaseyManning

Added an operator button that will calibrate the exposure on the camera. Includes a version using sockets so that we can test if sockets work in the future.

2017-02-22 02:31 UTC, billwpierce commented on src/org/usfirst/frc4904/robot/commands/CalibrateCameraExposureSockets.java
> +	protected boolean isFinished() {
Can you put this after execute for simplicities sake?

2017-02-22 02:34 UTC, billwpierce requested changes
Mostly fine, except get rid of the main function (it probably won't test), and are you sure you tested? The main function should've broken everything.

2017-02-22 02:34 UTC, billwpierce commented on src/org/usfirst/frc4904/robot/commands/CalibrateCameraExposureSockets.java
> +	public static void main(String[] args) {
Please remove this main command. It would probably break things.

2017-02-22 02:34 UTC, billwpierce commented on src/org/usfirst/frc4904/robot/humaninterface/HumanInterfaceConfig.java
> +	public static final int TEENSY_STICK_NUM_BUTTONS = 30;
Thanks for adding this.

2017-02-22 02:34 UTC, billwpierce commented on src/org/usfirst/frc4904/robot/humaninterface/operators/DefaultOperator.java
> +		RobotMap.Component.teensyStick.getButton(15).whenPressed(new CalibrateCameraExposure());
Are we sure this button isn't being used by anything else? Just curious.

2017-02-22 02:36 UTC, billwpierce commented
I removed the 'tested' tag because I'm skeptical that it actually was.

2017-02-22 03:01 UTC, CaseyManning commented on src/org/usfirst/frc4904/robot/humaninterface/operators/DefaultOperator.java
> +		RobotMap.Component.teensyStick.getButton(15).whenPressed(new CalibrateCameraExposure());
I will have to talk to Nikhil about this, I believe that he has the master list of buttons, but he was the one that set it to fifteen, so it should be correct.

2017-02-22 03:02 UTC, CaseyManning commented on src/org/usfirst/frc4904/robot/commands/CalibrateCameraExposureSockets.java
> +	public static void main(String[] args) {
I did test it, but for only testing the networking, i didn't need to deploy to the robot, so I just ran it with a main function for testing purposes.

2017-03-09 23:02 UTC, c0d3rman approved these changes

2017-03-09 23:03 UTC, c0d3rman commented
@billwpierce Please re-review

2017-03-11 03:43 UTC, billwpierce approved these changes
Looks fine.

2017-03-11 21:51 UTC, merged