Directional autoshift
RoboticsTeam4904/2017-Code pull request #72
Opened 2017-03-11 03:46 UTC by billwpierce

Makes it automatically upshift if flooring and heading down the direction of the field.

2017-03-14 23:21 UTC, ajnadel commented
Autoshifting has changed significantly since this PR was made – can you update it?

2017-03-14 23:25 UTC, ajnadel requested changes

2017-03-14 23:25 UTC, ajnadel commented on src/org/usfirst/frc4904/robot/commands/AutoShifter.java
> +		boolean isGoingDownTheField = Math.abs(navxYaw) <= 30 || Math.abs(navxYaw) >= 150;
The NavX goes from -180 to +180, so this whole condition should change.

2017-03-14 23:56 UTC, ajnadel approved these changes

2017-03-18 00:09 UTC, billwpierce commented
@ajnadel please make sure I didn't break anything with what I just did. (I think I might've made a mistake lol)

2017-03-26 17:59 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/commands/AutoShifter.java
> +		boolean isGoingDownTheField = Math.abs(navxYaw) <= 30;
no magic numbers

2017-03-26 17:59 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/commands/AutoShifter.java
> +		boolean isGoingDownTheField = Math.abs(navxYaw) <= 30;
also, you probably want to test the number

2017-03-26 18:14 UTC, billwpierce commented on src/org/usfirst/frc4904/robot/commands/AutoShifter.java
> +		boolean isGoingDownTheField = Math.abs(navxYaw) <= 30;
@NikhilSuresh24 do you mean the number 30?

2017-03-26 18:19 UTC, NikhilSuresh24 commented on src/org/usfirst/frc4904/robot/commands/AutoShifter.java
> +		boolean isGoingDownTheField = Math.abs(navxYaw) <= 30;
i got it

2017-03-26 18:39 UTC, billwpierce commented on src/org/usfirst/frc4904/robot/commands/AutoShifter.java
> +		boolean isGoingDownTheField = Math.abs(navxYaw) <= 30;
@NikhilSuresh24 thanks. The only reason I haven't tested is because time with the robot is limited.

2017-03-26 18:40 UTC, billwpierce commented
@NikhilSuresh24 I think you misnamed the variable...

2017-04-11 18:35 UTC, billwpierce commented
Made obsolete by fancy-autoshift

2017-04-11 18:35 UTC, closed without merging